### PR TITLE
Page | Organisation

### PR DESCRIPTION
**Pull request by edwinmp**
image

image

### CODE REVIEW

**Comment by edwinmp** [comment]
Not sure how to best handle API errors, the error messages to display. I'm currently just logging them on the console but we should at least show some generic feedback.

**Review by nosvalds — CHANGES_REQUESTED** [review]
Looking good! I like the new style of the loader and not making the color of the whole like of text the same as the status. Mobile looks good!

Feedback:
* Missing the logo and description for organisations that have them. See https://iativalidator.iatistandard.org/organisation/usaid
* Not sure if this [ticket](https://trello.com/c/9pKVu73Q) would be easy to fix now or you'd like to save it for when you figure out the sorting/filtering for the table
* Seeing some text-wrapping issues for long filenames
image

**Comment by edwinmp** [comment]
@nosvalds worked on the feedback ... I've failed to load the reports for UNICEF, not sure if it's just a problem on my end. Anyway, let me know if you run into any edge cases.

**Review by nosvalds — APPROVED** [review]
- Seeing the logo/description now. Although wondering if we want to keep the same styling where the logo is to the right of the description vs. above it.
- I still don't love the look when you hover on a long name, but I won't let it hold up this PR. Wrote this [ticket](https://trello.com/c/BqecAw5Y) 
image
- UNICEF will eventually load for me but it takes forever. I think you mentioned this before but can you suggest what we should remove from the API call on the backend to make this more efficient in a ticket that I can pickup? I think we don't need MOST of the validation report (just the summary to get the status), but are serving it up currently.

**Pull request merged**
