### PR TITLE
Page | Validate

### PR DESCRIPTION
**Pull request by edwinmp**
For the Check Data feature

### CODE REVIEW

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Review

Overall it looks really nice. I like the change in UI since I think the majority of the time folks will just do a file upload vs. the URL. 

Most of the behaviour is the same. I can only choose `.xml` files in my file browser. If I try a file that is over 60 MB I get an error.

## Issues

### Can't view Report for files with a Critical Status

1. Upload file that has critical errors
2. Go to table view
3. Try clicking the file row in table with the Critical status, nothing happens. 

Workspace:
http://localhost:4200/validate/l95cpsp628vy25wcy06i

image

Also seems to intermittently drop this error in the console:

```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 4
```

Here are example XML files you can use to reproduce:

- https://github.com/IATI/js-validator-api/blob/develop/integration-tests/test-files/iati-act-schema-errors.xml
- https://raw.githubusercontent.com/IATI/js-validator-api/develop/integration-tests/test-files/iati-org-schema-errors.xml

This is also a directory of all the XML files we use to test the validator API if helpful:
https://github.com/IATI/js-validator-api/tree/develop/integration-tests/test-files

### Missing Error handling for bad URLs

1. Try uploading Url: https://httpbin.org/status/400
4. It says file has been uploaded successfully

image

5.In console 422 error
 
```
XHRPOSThttps://dev-api.iatistandard.org/vs/pvt/adhoc/url?sessionId=l95dkvqfhzgzr64v5te&url=https://httpbin.org/status/400&guid=65ac92f5-e5d3-4400-bd4f-958dfb56a414
[HTTP/2 422 Unprocessable Entity 364ms]

```

Live Validator handles this:

image

Similar for URLs:

- https://httpbin.org/status/500
- https://expired.badssl.com/

### Spinny Loaders missing in table view

When first on the `/validate/<session_id>` page after uploading a file there isn't a progress indicator that the file is being processed. This is present on the current validator and important for larger files that will take up to 3-4min to validate.

vue validator:
image

live validator:
image

**Comment by edwinmp** [comment]
@nosvalds feedback resolved. Also added the file size validation.

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Fixed 

- Spinny loaders
- Error handling for bad URL uploads
- Critical Error validation report links

## Issues

### URL Upload showing error for good URLs

I always get an error when I upload a good URL now:

image

However, when you go to the workspace it seems to have actually worked just fine

image

**Review by nosvalds — APPROVED** [review]
Looks great!

**Pull request merged**
